name: Label issues

on:
  issues:
    types: [opened]

env:
  PROJECT_NAME: Michi

jobs:
  assign_issue_to_project:
    name: Assign issues to project
    runs-on: ubuntu-latest
    steps:
      - name: Assign issues to project
        uses: technote-space/create-project-card-action@v1
        if: "github.event.action == 'opened'"
        with:
          PROJECT: ${{env.PROJECT_NAME}}
          COLUMN: Backlog
