name: Add Issue to Project and Set Status

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Add Issue and Set Status
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        id: add-project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/nagokos/projects/4
          github-token: ${{ secrets.WORKFLOWS_TOKEN }}

      - name: Set status to backlog
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.WORKFLOWS_TOKEN }}
          script: |
            await github.graphql(`
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                updateProjectV2ItemFieldValue(
                  input: {
                    projectId: $projectId,
                    itemId: $itemId,
                    fieldId: $fieldId,
                    value: {
                      singleSelectOptionId: $optionId
                    }
                  }
                ) {
                  projectV2Item {
                    id
                  }
                }
              }
            `, {
              projectId: process.env.PROJECT_ID,
              itemId: process.env.ITEM_ID,
              fieldId: process.env.STATUS_ID,
              optionId: process.env.BACKLOG_ID
            });
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          ITEM_ID: ${{ steps.add-project.outputs.itemId }}
          STATUS_ID: ${{ secrets.STATUS_ID }}
          BACKLOG_ID: ${{ secrets.BACKLOG_ID }}
